image: Visual Studio 2017

platform: x64

install:
  # None of the packaged channels are new enough for the current state
  # of FDE, so for now clone master instead.
  #- ps: build\ci\install_flutter.ps1 $env:APPVEYOR_BUILD_FOLDER\..
  - git clone -b master https://github.com/flutter/flutter.git %APPVEYOR_BUILD_FOLDER%\..\flutter

build_script:
  - set "PATH=%APPVEYOR_BUILD_FOLDER%\..\flutter\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\;%PATH%"
  - set "ENABLE_FLUTTER_DESKTOP=true"
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\example"
  - flutter packages get
  - flutter build -v windows --debug
  - flutter build -v windows --release
  - ps: cd "$env:APPVEYOR_BUILD_FOLDER\testbed"
  - flutter packages get
  - flutter build -v windows --debug
