image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 16

cache:
  - node_modules
  - release/app/node_modules
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - cd client && npm install

test_script:
  - cd client
  - npm run package
  - npm run lint
  - npm test
  - npm test-e2e
